apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chess-game
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gorkememir/my-apps-platform
    targetRevision: release
    path: k8s
    directory:
      include: 'chess-app.yml'
  destination:
    server: https://kubernetes.default.svc
    namespace: chess-game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
    - name: syncInterval
      value: "30"
